kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pricelist-db-pvc
  namespace: pricelab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
